import { ApplicationConfig } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { LUCIDE_ICONS, LucideIconProvider } from 'lucide-angular';
import {
  Bot,
  Trash2,
  User,
  Copy,
  Check,
  Mic,
  MicOff,
  Send,
  Loader2,
  FileText,
  Sparkles,
  AlertTriangle,
  X,
  Eye,
  EyeOff,
  Lock,
  Mail,
  Plus,
  Search,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ArrowRight,
  Settings,
  HelpCircle,
  Calendar,
  TrendingUp,
  Activity,
  UserPlus,
  UserCog,
  Tag,
  Shield,
  Download,
  Pencil,
  CheckCircle2,
  Braces,
  Upload,
  Circle,
  Clock,
  PanelLeftClose,
  Menu,
  ShieldCheck,
  Bell,
  BellOff,
  LogOut,
  RefreshCw,
  LayoutDashboard,
  Users,
  UploadCloud,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from '../services/auth.interceptor';

// Icon set for global registration
const iconSet = {
  Bot,
  Trash2,
  User,
  Copy,
  Check,
  Mic,
  MicOff,
  Send,
  Loader2,
  FileText,
  Sparkles,
  AlertTriangle,
  X,
  Eye,
  EyeOff,
  Lock,
  Mail,
  Plus,
  Search,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ArrowRight,
  Settings,
  HelpCircle,
  Calendar,
  TrendingUp,
  Activity,
  UserPlus,
  UserCog,
  Tag,
  Shield,
  Download,
  Pencil,
  CheckCircle2,
  Braces,
  Upload,
  Circle,
  Clock,
  PanelLeftClose,
  Menu,
  ShieldCheck,
  Bell,
  BellOff,
  LogOut,
  RefreshCw,
  LayoutDashboard,
  Users,
  UploadCloud,
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider(iconSet),
    },
  ],
};
